# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x44\x46S\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x0b\x43\x61llRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tCallReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x0bRootRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\".\n\x0e\x46orwardMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06origin\x18\x02 \x01(\x05\",\n\x0c\x46orwardReply\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06origin\x18\x02 \x01(\x05\">\n\x0f\x42\x61\x63kwardMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x63hild\x18\x02 \x01(\x05\x12\x0e\n\x06parent\x18\x03 \x01(\x05\"\x1d\n\rBackwardReply\x12\x0c\n\x04type\x18\x01 \x01(\x05\":\n\x0bTreeMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05\x63hild\x18\x02 \x03(\x05\x12\x0e\n\x06parent\x18\x03 \x03(\x05\x32p\n\x07Greeter\x12\x30\n\x08SayHello\x12\x11.DFS.HelloRequest\x1a\x0f.DFS.HelloReply\"\x00\x12\x33\n\rCallNeighbors\x12\x10.DFS.CallRequest\x1a\x0e.DFS.CallReply\"\x00\x32\xac\x01\n\x03\x44\x46S\x12\x30\n\x08MakeRoot\x12\x10.DFS.RootRequest\x1a\x10.DFS.TreeMessage\"\x00\x12\x37\n\x0bSendForward\x12\x13.DFS.ForwardMessage\x1a\x11.DFS.ForwardReply\"\x00\x12:\n\x0cSendBackward\x12\x14.DFS.BackwardMessage\x1a\x12.DFS.BackwardReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=18
  _HELLOREQUEST._serialized_end=46
  _CALLREQUEST._serialized_start=48
  _CALLREQUEST._serialized_end=75
  _HELLOREPLY._serialized_start=77
  _HELLOREPLY._serialized_end=106
  _CALLREPLY._serialized_start=108
  _CALLREPLY._serialized_end=136
  _ROOTREQUEST._serialized_start=138
  _ROOTREQUEST._serialized_end=165
  _FORWARDMESSAGE._serialized_start=167
  _FORWARDMESSAGE._serialized_end=213
  _FORWARDREPLY._serialized_start=215
  _FORWARDREPLY._serialized_end=259
  _BACKWARDMESSAGE._serialized_start=261
  _BACKWARDMESSAGE._serialized_end=323
  _BACKWARDREPLY._serialized_start=325
  _BACKWARDREPLY._serialized_end=354
  _TREEMESSAGE._serialized_start=356
  _TREEMESSAGE._serialized_end=414
  _GREETER._serialized_start=416
  _GREETER._serialized_end=528
  _DFS._serialized_start=531
  _DFS._serialized_end=703
# @@protoc_insertion_point(module_scope)
