version: "3"

services:
  n1:
    build:
      context: .
      args:
        PORT: 50051
        NODE_ID: 1
    volumes:
      - ./output:/grpc-docker/ddfs/output
    networks:
      frontend:
        ipv4_address: "172.20.0.11"
    command: /bin/sh -c 'python3 dfs_server1.py'
    container_name: node1

  n2:
    build:
      context: .
      args:
        PORT: 50051
        NODE_ID: 2
    networks:
      frontend:
        ipv4_address: "172.20.0.12"
    command: /bin/sh -c 'python3 dfs_server1.py'
    container_name: node2


  n3:
    build:
      context: .
      args:
        PORT: 50051
        NODE_ID: 3
    networks:
      frontend:
        ipv4_address: "172.20.0.13"
    command: /bin/sh -c 'python3 dfs_server1.py'
    container_name: node3

  
  
networks:
  frontend:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
 
