version: "3"

services:
  server:
    build: .
    ports:
      - "50051:50051"
    command: tail -f /dev/null
    networks:
      frontend:
        ipv4_address: "172.20.0.10"



networks:
  frontend:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
 
