version: "3"

services:
  server:
    build: .
    ports:
      - "50051:50051"
    networks:
      frontend:
        ipv4_address: "172.20.0.10"
    command: tail -F anything
  node_1:
    build: "redis:alpine"
    networks:
      frontend:
        ipv4_address: "172.20.0.11"
    command: tail -F anything

networks:
  frontend:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
 
